import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useAppSelector, useAppDispatch } from "../app/hooks";
import { getArtworksAsync } from "../features/artworks/artworksSlice";
import { useEffect } from "react";
import { ArtCard } from "../features/artworks/components/ArtCard";
import { Controller } from "../Components/Controller";

const IndexPage: NextPage = () => {
  const dispatch = useAppDispatch();
  const artworks = useAppSelector((state) => state.artworks);
  const search = useAppSelector((state) => state.artworks.search);
  useEffect(() => {
    if (!search) {
      dispatch(getArtworksAsync({ page: 1, pageLimit: 25 }));
    }
  }, []);
  if (artworks.status === "pending") {
    return <h1>Loading...</h1>;
  } else if (artworks.status === "rejected") {
    return <h1>Rejected</h1>;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <Controller pagination={artworks.pagination} />
      <div className={styles.cardsContainer}>
        {artworks.list.map((item) => {
          return <ArtCard key={item.id} artwork={item} />;
        })}
      </div>
    </div>
  );
};

export default IndexPage;
